created contact page
kailashchoudhary11/imgman pull request #67
Opened 2022-10-24 15:23 UTC by musavveer

Please Provide The following Details About your PR

Type x Inside the checkbox to tick it

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #25 

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have attached the screenshot.
<img width="1680" alt="Screenshot 2022-10-24 at 8 52 12 PM" src="https://user-images.githubusercontent.com/62888562/197563923-c7add377-1b18-451e-b688-a9c755cf0641.png">

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-10-24 16:55 UTC, kailashchoudhary11 requested changes

2022-10-24 16:55 UTC, kailashchoudhary11 commented on templates/contact.html
> +      <input type="text" id="fname" name="firstname" placeholder="Full Name..">
```suggestion
      <input type="text" id="name" name="name" placeholder="Full Name..">
```

2022-10-24 16:55 UTC, kailashchoudhary11 commented on templates/contact.html
> +      <label for="fname">Name</label>
```suggestion
      <label for="name">Name</label>
```

2022-10-24 16:55 UTC, kailashchoudhary11 commented on templates/contact.html
> +    <form action="/action_page.php">
```suggestion
    <form method="post">
```

2022-10-24 16:55 UTC, kailashchoudhary11 commented on templates/contact.html
> +      <label for="lname">Email</label>
```suggestion
      <label for="email">Email</label>
```

2022-10-24 16:55 UTC, kailashchoudhary11 commented on templates/contact.html
> +      <input type="text" id="lname" name="email" placeholder="Email">
```suggestion
      <input type="text" id="email" name="email" placeholder="Email">
```

2022-10-24 16:56 UTC, kailashchoudhary11 commented
@musavveer try to use classes and ids for css instead of targeting elements!

2022-10-25 03:55 UTC, kailashchoudhary11 approved these changes
Looks Good to me

2022-10-25 03:56 UTC, merged

2022-10-25 03:56 UTC, kailashchoudhary11 commented
@musavveer  Don't Forget to Star the Repository!

2022-10-25 03:58 UTC, musavveer commented
> @musavveer Don't Forget to Star the Repository!

Do include hacktoberfest accepted label .>>>

2022-10-25 03:59 UTC, kailashchoudhary11 commented
> > @musavveer Don't Forget to Star the Repository!
> 
> Do include hacktoberfest accepted label .>>>

it is not required all the PRs to repo are included for hacktoberfest